# This workflow checks if a PR commit has changed the size of a hello world Rust program.
# It downloads Rustc and compiles two versions of a stage0 compiler - one using the base commit
# of the PR, and one using the latest commit in the PR.
# If the size of the hello world program has changed, it posts a comment to the PR.
name: Check binary size

on:
  pull_request_target:
    branches:
      - master

jobs:
  test:
    name: Check binary size
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: |
          mkdir foo
          echo "foo" > foo/test.txt
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: foo
          key: ${{ runner.os }}-primes
