# This workflow posts a comment after the Check binary size workflow finishes.
# It is in a separate workflow to avoid running untrusted code with elevated permissions in the
# Check binary size workflow
name: Post binary size

on:
  workflow_run:
    workflows: [Check binary size]
    types:
      - completed

jobs:
  post:
    name: Post binary size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
      - name: Display binary size
        run: |
          ls -la binaries/binary-*
          echo "SIZE_REFERENCE=$(stat -c '%s' binaries/binary-reference)" >> "$GITHUB_ENV"
          echo "SIZE_UPDATED=$(stat -c '%s' binaries/binary-updated)" >> "$GITHUB_ENV"
      - name: Post a PR comment if the size has changed
        uses: actions/github-script@v6
        with:
          script: |
            const reference = process.env.SIZE_REFERENCE;
            const updated = process.env.SIZE_UPDATED;
            const diff = updated - reference;
            const plus = diff > 0 ? "+" : "";
            const diff_str = `${plus}${diff}B`;
            
            if (diff !== 0) {
              const percent = (((updated / reference) - 1) * 100).toFixed(2);
              // The body is created here and wrapped so "weirdly" to avoid whitespace at the start of the lines,
              // which is interpreted as a code block by Markdown.
              const body = `Below is the size of a hello-world Rust program linked with libstd with backtrace.
            
            Original binary size: **${reference}B**
            Updated binary size: **${updated}B**
            Difference: **${diff_str}** (${percent}%)`;
            
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              })
            }
